name: Analyze with Knip
on:
    push:
        branches:
            - main
    pull_request:

jobs:
    knip:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Read .nvmrc
              run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
              id: nvm

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "${{ steps.nvm.outputs.NODE_VERSION }}"

            - name: Install dependencies
              run: npm install

            - name: Run Knip analysis
              run: npm run knip:check
