name: Check Build

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    check-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - uses: actions/setup-node@v7
              with:
                  node-version-file: .nvmrc

            - name: Install dependencies
              run: npm install

            - name: Run build check
              run: npm run build
